version: '3.1'

services:
  db:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080